import type {
  AvatarExportFormatDescriptor,
  AvatarFormatDescriptor,
  MotionExportFormatDescriptor,
  MotionFormatDescriptor,
} from "./types";

export const MOTION_FORMATS = [
  {
    id: "mixamo-fbx",
    role: "motion",
    label: "Mixamo FBX Motion",
    extensions: [".fbx"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "vrma",
    role: "motion",
    label: "VRM Animation",
    extensions: [".vrma"],
    mimeTypes: ["model/gltf-binary"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "bvh",
    role: "motion",
    label: "BVH Motion",
    extensions: [".bvh"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "vmd",
    role: "motion",
    label: "VMD Body Motion",
    extensions: [".vmd"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "gltf-animation",
    role: "motion",
    label: "glTF / GLB Animation",
    extensions: [".gltf", ".glb"],
    mimeTypes: ["model/gltf+json", "model/gltf-binary"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "actorcore-fbx",
    role: "motion",
    label: "ActorCore / Reallusion FBX Motion",
    extensions: [".fbx"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "generic-fbx",
    role: "motion",
    label: "Generic Humanoid FBX Motion",
    extensions: [".fbx"],
    availability: "available",
    assurance: "experimental",
  },
] as const satisfies readonly MotionFormatDescriptor[];

export const AVATAR_FORMATS = [
  {
    id: "vrm",
    role: "avatar",
    label: "VRM Avatar",
    extensions: [".vrm"],
    mimeTypes: ["model/gltf-binary"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "gltf-humanoid",
    role: "avatar",
    label: "glTF / GLB Humanoid Avatar",
    extensions: [".gltf", ".glb"],
    mimeTypes: ["model/gltf+json", "model/gltf-binary"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "mixamo-rigged",
    role: "avatar",
    label: "Mixamo-rigged Avatar",
    extensions: [".fbx", ".glb"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "ready-player-me",
    role: "avatar",
    label: "Ready Player Me Avatar",
    extensions: [".glb"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "mmd-model",
    role: "avatar",
    label: "MMD PMX / PMD Avatar",
    extensions: [".pmx", ".pmd"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "reallusion",
    role: "avatar",
    label: "Reallusion-compatible Avatar",
    extensions: [".fbx", ".glb"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "generic-fbx-avatar",
    role: "avatar",
    label: "Generic Humanoid FBX Avatar",
    extensions: [".fbx"],
    availability: "available",
    assurance: "experimental",
  },
] as const satisfies readonly AvatarFormatDescriptor[];

export const MOTION_EXPORT_FORMATS = [
  {
    id: "vrma",
    role: "motion-export",
    label: "VRMA",
    extensions: [".vrma"],
    mimeTypes: ["model/gltf-binary"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "motion-json",
    role: "motion-export",
    label: "Motion JSON",
    extensions: [".motion.json"],
    mimeTypes: ["application/json"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "vmd",
    role: "motion-export",
    label: "VMD",
    extensions: [".vmd"],
    mimeTypes: ["application/octet-stream"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "gltf-animation",
    role: "motion-export",
    label: "glTF / GLB Animation",
    extensions: [".glb", ".gltf"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "bvh",
    role: "motion-export",
    label: "BVH",
    extensions: [".bvh"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "fbx-animation",
    role: "motion-export",
    label: "FBX Animation",
    extensions: [".fbx"],
    availability: "available",
    assurance: "beta",
  },
] as const satisfies readonly MotionExportFormatDescriptor[];

export const AVATAR_EXPORT_FORMATS = [
  {
    id: "animated-glb",
    role: "avatar-export",
    label: "Animated GLB",
    extensions: [".glb"],
    mimeTypes: ["model/gltf-binary"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "vrm-external-vrma",
    role: "avatar-export",
    label: "VRM + external VRMA",
    extensions: [".zip"],
    mimeTypes: ["application/zip"],
    availability: "available",
    assurance: "beta",
  },
  {
    id: "baked-vrm",
    role: "avatar-export",
    label: "VRM 1.0 with embedded animation (experimental)",
    extensions: [".vrm"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "fbx-avatar-animation",
    role: "avatar-export",
    label: "Animated FBX",
    extensions: [".fbx"],
    availability: "available",
    assurance: "experimental",
  },
  {
    id: "animated-pmx",
    role: "avatar-export",
    label: "PMX Motion Morphs",
    extensions: [".pmx"],
    availability: "available",
    assurance: "experimental",
  },
] as const satisfies readonly AvatarExportFormatDescriptor[];
